
export const ERAS = [
  {
    id:"taylor-swift",
    name: "Taylor Swift",
    color1: "#A9CBAA",
    color2: " #0C1A0C",
    banner: "debut",
  },
  {
    id:"fearless",
    name: "Fearless",
    color1: "#FDDAA6",
    color2: " #1E151A",
    banner: "fearless",
  },
  {
    id:"speak-now",
    name: "Speak Now",
    color1: "#D6BADC",
    color2: " #000000",
    banner: "speak-now",
  },
  {
    id:"red",
    name: "Red",
    color1: "#72333C",
    color2: " #C7B2A2",
    banner: "red",
  },
  {
    id:"one989",
    name: "1989",
    color1: "#034A62",
    color2: " #D1F3FF",
    banner: "1989",
  },
  {
    id:"reputation",
    name: "Reputation",
    color1: "#2A2628",
    color2: " #CACACA",
    banner: "reputation",
  },
  {
    id:"lover",
    name: "Lover",
    color1: "#FBB3D1",
    color2: " #3D2D34",
    banner: "lover",
  },
  {
    id:"folklore",
    name: "folklore",
    color1: "#D5D5D5",
    color2: " #000000",
    banner: "folklore",
  },
  {
    id:"evermore",
    name: "evermore",
    color1: "#E0C9AF",
    color2: " #2E2327",
    banner: "evermore",
  },
  {
    id:"midnights",
    name: "Midnights",
    color1: "#E0EDFD",
    color2: " #1F2E43",
    banner: "midnight",
  },
];
